from turtle import Turtle, done,Screen

alamir = Turtle()
alamir.shape("turtle")
alamir.color("green")
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.left(90)
alamir.color("yellow")
alamir.circle(50)
alamir.color("blue")
alamir.write("Hello, I am Alamir Wagaw")
alamir.color("red")
alamir.right(90)        
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.color("blue")
alamir.write("Hello, I am Alamir Wagaw")
alamir.color("black")
alamir.right(90)        
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.right(90)        
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.right(90)
alamir.forward(100)
alamir.left(90)
alamir.forward(100)
alamir.goto(0,0)
done()
print(alamir)